### ISSUE TITLE
Version 1.7.0

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/Seeloewen-Shutdown#11]
## To-Do list for 1.7.0

Please note that 1.7.0 will be a big update so it's gonna take a while. Currently aiming at Q1-Q2 2022.

- [x] Redesign all windows
- [x] Remove 'message' feature
> The 'message' feature will be removed due to it being kinda useless and it wouldn't fit in with the new design.
- [x] Add debug log
- [x] Rework 'Stop running actions' option
> An auto detection for running actions will be added
- [x] Fix #10 
> The updater will be removed completely from the application
- [x] Fix #12
- [x] Add translations and darkmode for new stuff

**Comment by Seeloewen** [comment]
For anyone wondering, I'm already working on the redesign but in a seperate private repository. I will move the changes over to the public repository when a prototype of the new design is done and the application is somewhat usable.

**Comment by Seeloewen** [comment]
![image](https://user-images.githubusercontent.com/74246933/147835246-5148a432-f44a-48c1-829f-d5aad1613cd6.png)
First screenshot :)
This probably close to the final design, but not 100% done of course!

**Comment by Seeloewen** [comment]
Most of the big stuff is done, sorry for the long break

**Comment by Seeloewen** [comment]
![image](https://user-images.githubusercontent.com/74246933/156941241-cbdb0e82-0bc9-4486-b2b2-485ca5e6d16d.png)
(No action running)

![image](https://user-images.githubusercontent.com/74246933/156941260-7efa46cf-8e57-4659-a1de-e8bcb1cfd25d.png)
(Action running)

Probably final design

**Comment by Seeloewen** [comment]
Mostly done now, only need to add some more darkmode and translations and fix final bugs. Release 1.7.0 expected sometime around this weekend or next week.

**Comment by Seeloewen** [comment]
Update is done and will release soon.

**Comment by Seeloewen** [comment]
Released, though there are several small improvements and fixes alreadyplanned that have not been included in this build.
An update, probably called 1.7.1, can be expected in the next days/weeks.
