### ISSUE TITLE
Version 1.7.1

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/Seeloewen-Shutdown#13]
## To-Do list for 1.7.1
1.7.1 will feature several improvements and bug fixes. Expected to be released around March/April 2022.

- [x] Fix the bug, that the 'Start Action' buttons sometimes isn't translated correctly
- [x] Fix the bug, that the debug-log colors get reset if you change design
- [x] Fix typo in 'Start action' button
- [x] Fix log losing all its content upon reopening
- [x] Fix several typos in log messages

This list is subject to change if more bugs are found during development.

**Comment by Seeloewen** [comment]
Will not start working on this right away, won't take too long though.

**Comment by Seeloewen** [comment]
First bug is fixed, second one regarding the debug-log might take a little longer as it needs more work.

**Comment by Seeloewen** [comment]
Might have actually found and easier way, I'll check that tomorrow

Easier way:
- [ ] Remove code that changes textcolor of log
- [ ] Make textcolor of critical log error red

I'll make it so the forecolors of the log can stay exactly the same across all design so there will be no need to change them.

**Comment by Seeloewen** [comment]
After several changes in the log system it now works fine. Update releasing soon.
